apiEndpoints:
  users:
    host: '*'
    paths: ['/users']
    scopes: #by defyning this attribute you can assigne scopes to endpoints
      - scope: Admin # assumes scopes *
      - scope: User
        verbs: GET
      - scope: Manager
        verbs: [GET, POST, PUT]

serviceEndpoints:
  backend:
    url: 'http://www.example.com'
pipelines:
  -
    name: ecommerce
    apiEndpoints:
       - users
    policies:
        - condition:
              name: always
          action:
              name: proxy
              serviceEndpoint: backend
