version: 2
jobs:
  "node-6":
    docker:
      - image: circleci/node:6-browsers
    working_directory: ~/repo

    steps: &steps
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm test

  "node-8":
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo

    steps: *steps

  "node-10":
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo

    steps: *steps

  "node-8-real-redis":
    docker:
      - image: circleci/node:8-browsers
      - image: circleci/redis
    working_directory: ~/repo
    environment:
      - EG_DB_EMULATE: false
    steps: *steps

  "release-npm":
    docker:
      - image: circleci/node:8
    working_directory: ~/repo

    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish

  "release-docker-images":
    docker:
      - image: circleci/node:8
    working_directory: ~/repo

    steps:
      - run: apk add hub
      - run: hub clone https://github.com/ExpressGateway/docker-express-gateway.git .
      - run: npm ci
      - run: node index.js
      - run: hub commit -am 'Update Express Gateway Images'
      - run: hub push

  packer:
    docker:
      - image: hashicorp/packer:light
    working_directory: ~/repo

    steps:
      - checkout
      - run: packer build ./.circleci/packer.json

workflows:
  version: 2
  build:
    jobs:
      - node-6: &testingFilters
          filters:
            tags:
              only: /v\d+(\.\d+){2}/
      - node-8: *testingFilters
      - node-10: *testingFilters
      - node-8-real-redis: *testingFilters
      - release-npm: &releaseFilters
          filters:
            tags:
              only: /v\d+(\.\d+){2}/
            branches:
              ignore: /.*/
          requires:
            - node-6
            - node-8
            - node-8-real-redis
            - node-10
      - release-docker-images: *releaseFilters
      - packer: *releaseFilters

