version: 2
jobs:
  "node-8":
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo

    steps: &eg-checkout-install
      - checkout
      - run: npm ci
      - run: npm test

  "node-10":
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo

    steps: *eg-checkout-install

  "node-12":
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo

    steps: *eg-checkout-install


  "node-10-real-redis":
    docker:
      - image: circleci/node:10-browsers
      - image: circleci/redis
    working_directory: ~/repo
    environment:
      - EG_DB_EMULATE: false
    steps: *eg-checkout-install

  "release-npm-docker-image":
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish
      - run: "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin"
      - run: "docker build -t expressgateway/express-gateway:${CIRCLE_TAG} -t expressgateway/express-gateway:latest --build-arg EG_VERSION=latest ."
      - run: "docker push expressgateway/express-gateway:${CIRCLE_TAG}"
      - run: "docker push expressgateway/express-gateway:latest"

  "update-docker-repo":
    docker:
      - image: node:10-alpine
    working_directory: ~/repo

    steps:
      - run: &setup_container
          name: Setup container with Git, Hub, OpenSSH and trust GitHub key
          command: |-
            echo "http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
            apk add --update hub git openssh-client
            mkdir ~/.ssh && ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            git config --global user.email $GITHUB_EMAIL
            git config --global user.name $GITHUB_NAME
      - run:
          name: Clone the EG's docker repository
          command: hub clone ExpressGateway/docker-express-gateway .
      - run:
          name: Install automation script dependencies
          command: npm ci
      - run:
          name: Generate new Helm and Docker files
          command: node index.js
          environment:
            - EG_CHART_VERSION: 1.6.3
      - run:
          name: Create new commit with the changes
          command: hub commit -sam "Update Express Gateway Images to $CIRCLE_TAG"
      - run:
          name: Push changes to the upstream server
          command: hub push -f
      - run:
          name: Save commit to file
          command: git rev-parse HEAD > DockerCommit
      - persist_to_workspace:
          root: ./
          paths:
            - Helmfile
            - Helmvaluefile
            - Helmreadme
            - DockerCommit

  "update-helm-charts":
    docker:
      - image: alpine
    working_directory: ~/repo
    steps:
      - run: *setup_container
      - run:
          name: Fork the official helm charts repo
          command: |-
            hub clone helm/charts .
            hub fork
      - attach_workspace:
          at: ./
      - run:
          name: Copy new files in charts
          command: |-
            cp Helmfile ./stable/express-gateway/Chart.yaml
            cp Helmvaluefile ./stable/express-gateway/values.yaml
            cp Helmreadme ./stable/express-gateway/README.md
      - run:
          name: Commit and push changes
          command: hub commit -sam "Update Express Gateway Images to $CIRCLE_TAG" && hub push -f -u eg-bot master
      - run: &createPR
          name: Create Pull Request
          command: hub pull-request -m "Update Express Gateway Images to $CIRCLE_TAG"

  "update-official-docker-image":
    docker:
      - image: alpine
    working_directory: ~/repo
    steps:
      - run: *setup_container
      - run:
          name: Fork the official docker image repository
          command: |-
            hub clone docker-library/official-images .
            hub fork
      - attach_workspace:
          at: ./
      - run:
          name: Put new commit id
          command: "val=$(cat DockerCommit) && sed -i \"s/GitCommit: .*/GitCommit: $val/g\" library/express-gateway"
      - run:
          name: Commit and push changes
          command: |-
            hub add library/express-gateway
            hub commit -m "Update Express Gateway Images to $CIRCLE_TAG"
            hub push -f -u eg-bot master
      - run: *createPR

workflows:
  version: 2
  build:
    jobs:
      - node-8: &testingFilters
          filters:
            tags:
              only: /v\d+(\.\d+){2}/
      - node-10: *testingFilters
      - node-12: *testingFilters
      - node-10-real-redis: *testingFilters
      - release-npm-docker-image:
          filters: &releaseFilters
            tags:
              only: /v\d+(\.\d+){2}/
            branches:
              ignore: /.*/
          requires:
            - node-8
            - node-10-real-redis
            - node-10
            - node-12
      - update-docker-repo: &postNpmPublish
          requires:
            - release-npm-docker-image
          filters: *releaseFilters
      - update-helm-charts: &docker-repo-first
          requires:
            - update-docker-repo
          filters: *releaseFilters
      - update-official-docker-image: *docker-repo-first
