version: 2
jobs:
  "node-6":
    docker:
      - image: circleci/node:6-browsers
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm test

  "node-8":
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm test

  "node-10":
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm test

  "node-8-real-redis":
    docker:
      - image: circleci/node:8-browsers
      - image: circleci/redis
    working_directory: ~/repo
    environment:
      - EG_DB_EMULATE: false
    steps:
      - checkout
      - run: npm install
      - run: npm test

  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish
      - run: "docker build -t expressgateway/express-gateway:${CIRCLE_TAG} --build-arg EG_VERSION=latest ."
      - run: "docker tag expressgateway/express-gateway:${CIRCLE_TAG} expressgateway/express-gateway:latest"
      - run: "docker push expressgateway/express-gateway:${CIRCLE_TAG}"
      - run: "docker push expressgateway/express-gateway:latest"

workflows:
  version: 2
  build:
    jobs:
      - node-6:
          filters:
            tags:
              only: /v\d+(\.\d+){2}/
      - node-8:
          filters:
            tags:
              only: /v\d+(\.\d+){2}/
      - node-10:
          filters:
            tags:
              only: /v\d+(\.\d+){2}/
      - node-8-real-redis:
          filters:
            tags:
              only: /v\d+(\.\d+){2}/
      - deploy:
          filters:
            tags:
              only: /v\d+(\.\d+){2}/
            branches:
              ignore: /.*/
          requires:
            - node-6
            - node-8
            - node-8-real-redis
            - node-10
