version: 2
jobs:
  "node-6":
    docker:
      - image: circleci/node:6
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm test

  "node-8":
    docker:
      - image: circleci/node:8
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm test

  "node-8-real-redis":
    docker:
      - image: circleci/node:8
      - image: redis:alpine
    working_directory: ~/repo
    environment:
      - EG_DB_EMULATE: 0
    steps:
      - checkout
      - run: npm install
      - run: npm test

  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish
      - run: "docker build -t expressgateway/express-gateway:${CIRCLE_TAG} --build-arg VERSION=latest - < Dockerfile"
      - run: |
              "docker build -t expressgateway/express-gateway:${CIRCLE_TAG}-getting-started
               --build-arg VERSION=latest --build-arg TYPE=getting-started - < Dockerfile"
      - run: "docker tag expressgateway/express-gateway:${CIRCLE_TAG} expressgateway/express-gateway:latest"
      - run: "docker tag expressgateway/express-gateway:${CIRCLE_TAG}-getting-started expressgateway/express-gateway:latest"
      - run: "docker push expressgateway/express-gateway:${CIRCLE_TAG}"
      - run: "docker push expressgateway/express-gateway:${CIRCLE_TAG}-getting-started"
      - run: "docker push expressgateway/express-gateway:latest"
      - run: "docker push expressgateway/express-gateway:latest-getting-started"

workflows:
  version: 2
  build:
    jobs:
      - node-6
      - node-8
      - node-8-real-redis
      - deploy:
          filters:
            tags:
              only: /v\d+(\.\d+){2}/
            branches:
              ignore: /.*/
          requires:
            - node-8
            - node-6
